### ISSUE TITLE
Exception in file read

### ISSUE THREAD

**Issue by neerajkumaragarwal1990** [mashery/iodocs#225]
On mac, when I do `npm start`, I get this error.

File /Users/abc/projects/iodocs/config.json not found or is invalid.  Try: `cp config.json.sample config.json`

I tried printing the exception, it says 
[TypeError: Property 'minify' of object #<Object> is not a function]

I did `npm install` properly, I tried installing the `node-json-minify` manually as well, but still doesn't work. 
I tried using https://github.com/getify/JSON.minify on node command line as well, but it doesn't work as well. Should I try some other version of node-json-minify? It is set to 0.1.x right now in package.json

**Comment by amilkr** [comment]
It should be fixed.

**Comment by chipironcin** [comment]
It is still not fixed. Is there anyone managing the repo? Maybe a line in FAQ or warning in README.md will do the trick for new installs.

**Comment by nnoco** [comment]
@chipironcin Did you run "npm install" after to modify config.json?

**Comment by nnoco** [comment]
@ArVan Thank you! That solves it!
